/* Pookie BTC/ETH
POST IDENTICAL HASH Lock (immutable)
CONFIRM POST HASH LOCK KEY is 'immutable' STATUS
POST PROOF OF KEY DATA THAT WHEN HASHED EQUALS THE HASH LOCK
Mitzi VIAT
POST IDENTICAL HASH Lock (immutable)
CONFIRM POST HASH LOCK KEY is 'immutable' STATUS
POST PROOF OF HASH LOCK KEY TO CLAIM ASSETS
 */
// ANONYMOUS ATOMIC SWAPS & PRIVATE ATOMIC SWAPS
// (CAN BE STRICTER AND REQUIRE LINK TO OTHER NETWORK CONFIRMED BLOCK TO CLAIM ASSETS)
// (CAN ALSO INCLUDE A ONE TIME PUBLIC KEY TO RESTRICT IT TO A SPECIFIC ENTITY THAT HAS THE PRIVATE KEY THIS MEANS CRYPTO AGNOSTIC)
// AFTER A CERTAIN TIME OR BLOCK HEIGHT THE HASH LOCK EXPIRES & OR DOWNGRADES SO NO PRIVATE KEY IS REQUIRED
