export async function getAddressDirectoryPath() {
	// GET 3 BYTE PATH CONVERT TO ENCODING
	// GET 4-6 BYTE PATH CONVERT TO ENCODING
	// GET LAST 32 BYTES OF WALLET ADDDRESS CONVERT TO ENCODING
	// RETURN FULL PATH
}
