export const defaultStage = 0;
export const askRPC = {
	setup: 1,
	pathReady: 2,
	sendingPath: 3,
	parametersReady: 4,
	sendingParameters: 5,
	headReady: 6,
	sendingHead: 7,
	dataReady: 8,
	sendingData: 9,
	onSetup: 10,
	sendPathReady: 11,
	receivingPath: 12,
	sendParametersReady: 13,
	receivingParameters: 14,
	sendHeadReady: 15,
	receivingHead: 16,
	sendDataReady: 17,
	receivingData: 18,
	received: 19,
	sendEnd: 20,
	end: 21,
};
export const replyRPC = {
	onSetup: 1,
	sendPathReady: 2,
	receivingPath: 3,
	sendParametersReady: 4,
	receivingParameters: 5,
	sendHeadReady: 6,
	receivingHead: 7,
	sendDataReady: 8,
	receivingData: 9,
	received: 10,
	setup: 11,
	pathReady: 12,
	sendingPath: 13,
	parametersReady: 14,
	sendingParameters: 15,
	headReady: 16,
	sendingHead: 17,
	dataReady: 18,
	sendingData: 19,
	sendEnd: 20,
	end: 21,
};
